[session]
initial_positions = [[0.5, 0.0], [0.0, 5.0], [0.0, -5.0]]
leader_trajectory = "./data/straight_trajectory_data.npz"
save_name = "./data/straight_optimization_results_o2_log_v2.npz"
video_name = "./data/media/straight_optimization_results.mp4"

[model]
n_robots = 3
robot_mass = 1.0
interrobot_observation_kind = "distance"

[stlog]
order = 3
dt = 0.2

[opc]
window_size = 20
observed_components = [3, 4, 6, 7]
max_inter_vehicle_distance = -1
min_inter_vehicle_distance = -1

[optim]
method = "trust-constr"
ub = [4.0, 1.0]
lb = [0.0, -1.0]

[optim.options]
xtol = 1e-3
gtol = 1e-6
disp = false
verbose = 0
maxiter = 150

[sim]
steps = 500
