[session]
initial_positions = [
    [
        4,
        0,
        10.0,
    ],
    [
        -2.0,
        3.46410162,
        10.0,
    ],
    [
        -2.0,
        -3.46410162,
        10.0,
    ],
]
leader_trajectory = "./data/trajectory_data.npz"
save_name = "./data/optimization_results.npz"

[model]
n_robots = 3
robot_mass = 1.0

[stlog]
order = 2

[opc]
window_size = 40
observed_components = [10, 11, 12, 20, 21, 22]
min_inter_vehicle_distance = 1
max_inter_vehicle_distance = 8

[optim]
method = "trust-constr"
ub = [11.0, 0.4, 0.4, 2.0]
lb = [0.0, -0.4, -0.4, -2.0]

[optim.options]
xtol = 1e-1
gtol = 1e-4
disp = false
verbose = 0
maxiter = 150

[sim]
steps = 2000
