[model]
n_robots = 3
robot_mass = 1.0

[stlog]
order = 1

[opc]
window_size = 20
observed_components = [10, 11, 12, 20, 21, 22]
max_inter_vehicle_distance = 100
min_inter_vehicle_distance = 2

[initial_path]
degree = 5
derivative_weights = [0, 0, 1, 1]
time_reference = [0, 100]
position_reference = [
    [

        [2.0, 252.0],   # Force horizontal listing
        [0.001, 0.001],
        [10.0, 10.0],

    ],
    [
        [-0.001, 249.999], # Force horizontal listing
        [1.0, 1.0],
        [10.0, 10.0],
    ],
    [
        [0.0002, 250.0002], # Force horizontal listing
        [-1.0, -1.0],
        [10.0, 10.0],
    ],
]
n_timesteps = 500

[optim]
method = "trust-constr"
ub = [11.0, 0.4, 0.4, 2.0]
lb = [0.0, -0.4, -0.4, -2.0]

[optim.options]
xtol = 1e-1
gtol = 1e-4
disp = false
verbose = 0
maxiter = 150

[sim]
steps = 300
