[session]

n_samples = 50

load = "data/state_estimation_data.pkl"
save = "data/state_estimation_data.pkl"
image_save = "/home/hs293go/Documents/tex/hsgo-papers/papers/observability_aware_control/graphics/state_estimation_results_log.png"

[session.experimental_data]
"Uniform Motion" = { "file" = "./data/lemniscate_optimization_results_unoptimized.npz" }
"Optimized Order-1 STLOG" = { "file" = "./data/lemniscate_optimization_results_o1_log_v2.npz" }
"Optimized Order-2 STLOG" = { "file" = "./data/lemniscate_optimization_results_o2_log.npz" }

[model]
n_robots = 3
robot_mass = 1.0
